# Production docker-compose configuration
# Run with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
version: '3.8'

services:
  redis:
    # Production Redis configuration
    command: >
      redis-server
      --appendonly yes
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
    restart: always
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  queue-server:
    restart: always
    environment:
      # Production optimizations
      - LOG_LEVEL=warn
      - DEVELOPMENT=false
      - GOMAXPROCS=2
      - GOGC=100
      
      # Production security
      - JWT_SECRET=${JWT_SECRET}  # Use environment variable
      - API_KEYS=${API_KEYS}      # Use environment variable
      
      # Performance tuning
      - MAX_CONCURRENT_WORKERS=100
      - BATCH_SIZE=50
      - FLUSH_INTERVAL=5s
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  prometheus:
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=720h'  # 30 days
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  grafana:
    restart: always
    environment:
      # Production Grafana settings
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

  # Remove development tools
  redis-insight:
    profiles:
      - never  # Never start in production